### ISSUE TITLE
Unexpected outcome

### ISSUE THREAD

**Issue by ahangarha** [alihoseiny/word_cloud_fa#4]
**Describe the bug**
I run the example codes but get different results. For example this is what I get with mixed-example code:

![mixed-example](https://user-images.githubusercontent.com/11241315/75578710-f3747c80-5a81-11ea-8902-c95262d85be9.png)

**To Reproduce**
1. Running the same code as yours
2. Your environment (python 3.7.5, Ubuntu 19.10)

**Expected behavior**
Of course to get same result as yours

**Screenshots**
shared above

**Additional context**
I run the code in virtualenv.

**Comment by ahangarha** [comment]
Can it be because of some wrong version of dependencies? Because I see you haven't mentioned version of some dependencies in `setup.py` https://github.com/alihoseiny/word_cloud_fa/blob/412ba24281611a9bebc7e7b9c25f7c647d82b945/setup.py#L22

This is my the result of my `pip freeze`:
```
arabic-reshaper==2.0.15
cycler==0.10.0
future==0.18.2
hazm==0.7.0
kiwisolver==1.1.0
libwapiti==0.2.1
matplotlib==3.1.3
nltk==3.3
numpy==1.18.1
Pillow==7.0.0
pyparsing==2.4.6
python-bidi==0.4.2
python-dateutil==2.8.1
six==1.14.0
wordcloud==1.6.0
wordcloud-fa==0.1.6
```

**Comment by ahangarha** [comment]
Huge difference between v0.1.5 and v0.1.6

![image](https://user-images.githubusercontent.com/11241315/75581026-608a1100-5a86-11ea-96a4-f0dfe4f0026c.png)

**Comment by alihoseiny** [comment]
Thanks for your report. But it is the expected behavior. 
In the new version, we are using the Hazm parser instead of regex parser for getting more accurate results in Farsi texts. You can see new examples for mixed and English only versions for more information.
The brackets in your output produced because of the `include_numbers=False` parameter. You can solve them by adding them to stopwords like [new masked example](https://github.com/alihoseiny/word_cloud_fa/blob/master/Examples/masked-example.py).
